#import "../fragments/user.gql"

query users(
  $page: Int
  $sortDirection: SortDirection
  $sortBy: String
  $search: String
  $limit: Int
) {
  users(
    input: {
      page: $page
      sortDirection: $sortDirection
      sortBy: $sortBy
      search: $search
      limit: $limit
    }
  ) {
    pagination {
      page
      sortBy
      sortDirection
      total
      limit
    }

    results {
      ...UserFragment
    }
  }
}
